### ISSUE TITLE
How To Update Table

### ISSUE THREAD

**Issue by twoke** [expensivegasprices/BZObjectStore#12]
First .
Thank you.
It is a very nice project .

Next . I have question.
How to update the Database Table structure?
And. How to create auto increment column.

**Comment by expensivegasprices** [comment]
Thanks your issue!

> How to update the Database Table structure?

Table structure will be updated automatically when models changes.
(But, only deleting columns is not supported because of no support on sqlite.)
Please see for details. https://github.com/expensivegasprices/BZObjectStore/blob/master/BZObjectStore/Core/Classes/Migration/BZObjectStoreMigration.m 

> How to create auto increment column.

I'm developing this function now. : )

Regards

**Comment by twoke** [comment]
Thanks your answer .  : )
